name: Build & Release

on:
  push:
    tags:
      - v*

env:
  PYTHON_VERSION: '3.12'
  PYZULE-RW: 'https://github.com/asdfzxcvbn/pyzule-rw/archive/main.zip'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build-and-release-ios-ipa:
    permissions:
      contents: write
    runs-on: macos-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: setup rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: install the CLI tool
        run: cargo install 'flutter_rust_bridge_codegen'

      - name: flutter pub get
        run: flutter pub get

      - name: setup pyzule-rw
        run: |
          python -m pip install --upgrade pip
          pip install --force-reinstall ${{ env.PYZULE-RW }}

      - name: build ios
        run: |
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app-release.ipa Payload
          cyan -i app-release.ipa -o app-release-fakesign.ipa -uwsgq
          mv app-release-fakesign.ipa Mangayomi-${{ github.ref_name }}-ios.ipa

      - name: upload artifact ios ipa
        uses: actions/upload-artifact@v4
        with:
          name: Mangayomi-${{ github.ref_name }}-ios
          path: "build/ios/iphoneos/Mangayomi-*.ipa"

      - name: release package ios ipa
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/ios/iphoneos/Mangayomi-*.ipa"
          allowUpdates: true

  call-workflow-sideloading:
    needs: build-and-release-ios-ipa
    uses: ./.github/workflows/update_sideloading_source.yml